[workspace]
resolver = "2"

members = [
    "crates/fir",
    "crates/fir-wasm",
    "crates/fir-nvse",
    "crates/fir-geckscript",
    "crates/psyker",
    "crates/nvlsp",
    "crates/nv-types",
    "xtask",
]
exclude = [
    "win32",
    "geckstractor",
]
